version: '3'
services:
  web:
    build: ./web
    depends_on:
      - db
    environment:
      DB_HOST: db
    volumes:
      - ./web:/usr/src/app
    ports:
      - 80:80
  db:
    image: mariadb:10.3.5
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: web_data
      MYSQL_USER: web_user
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306

volumes:
  db_data: